// ============================================================
//  videosData.js
//  Shared video list — import this in BOTH HomePage and Video
// ============================================================

const videosData = [
  {
    id: 7679,
    thumbnail: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTu-l3JR0guZspKsBZkVoakjkQ-qxUCCpkQnw&s",
    title: "Big Buck Bunny open-source film",
    duration: "09:56",
    channel: "Laxminarayan",
    views: "1.4M",
    uploadedAt: "1 year ago",
    videoUrl: "https://download.blender.org/peach/bigbuckbunny_movies/BigBuckBunny_320x180.mp4",
  },
  {
    id: 2,
    thumbnail: "https://i.ytimg.com/vi/ScMzIvxBSi4/hqdefault.jpg",
    title: "Sample Video 2",
    duration: "30:00",
    channel: "Mummy",
    views: "980K",
    uploadedAt: "2 years ago",
    videoUrl: "https://media.w3.org/2010/05/sintel/trailer.mp4",
  },
  {
    id: 3,
    thumbnail: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTwyNTbTLzlbDj6RSQdV6imNyxNywT3pchKKg&s",
    title: "3d Lion Stock Photo",
    duration: "60:00",
    channel: "Papa",
    views: "540K",
    uploadedAt: "3 years ago",
    videoUrl: "https://download.blender.org/peach/bigbuckbunny_movies/BigBuckBunny_320x180.mp4",
  },
  {
    id: 4,
    thumbnail: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQpWv_QvC-7P4_8Ubbg2rwn0Om4APOgf6B3yA&s",
    title: "Sample Video 4",
    duration: "10:00",
    channel: "Karthik",
    views: "230K",
    uploadedAt: "6 months ago",
    videoUrl: "https://res.cloudinary.com/mashhuudanny/video/upload/v1720350210/xo81mxhcvjckkw1tdp62.mp4",
  },
  {
    id: 5,
    thumbnail: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRZleDiTkppd2k7GVmREMQRs8D8JBbNXuuxUA&s",
    title: "8k Wallpaper 3d Photos",
    duration: "18:00",
    channel: "Annu",
    views: "1.1M",
    uploadedAt: "1 year ago",
    videoUrl: "https://media.w3.org/2010/05/sintel/trailer.mp4",
  },
  {
    id: 6,
    thumbnail: "https://damassets.autodesk.net/content/dam/autodesk/www/industry/3d-animation/create-beautiful-3d-animations-thumb-1204x677.jpg",
    title: "3D Animation Solutions | Autodesk",
    duration: "08:00",
    channel: "Jyoti",
    views: "670K",
    uploadedAt: "8 months ago",
    videoUrl: "https://download.blender.org/peach/bigbuckbunny_movies/BigBuckBunny_320x180.mp4",
  },
  {
    id: 7,
    thumbnail: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTMxQZtpZz8NgMYzzNMiBm-n4h2oGYovjK2lQ&s",
    title: "3D Shapes | Types, Properties & Examples",
    duration: "28:00",
    channel: "Sarita",
    views: "420K",
    uploadedAt: "2 years ago",
    videoUrl: "https://res.cloudinary.com/mashhuudanny/video/upload/v1720350210/xo81mxhcvjckkw1tdp62.mp4",
  },
  {
    id: 8,
    thumbnail: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSK5izd-jLAR_UjqnUULPW42Pv_LIpL0W60cQ&s",
    title: "3d Graphics Pictures | Unsplash",
    duration: "20:00",
    channel: "Jaynarayan",
    views: "310K",
    uploadedAt: "1 year ago",
    videoUrl: "https://media.w3.org/2010/05/sintel/trailer.mp4",
  },
  {
    id: 9,
    thumbnail: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQN6EQg2_-8zTqUk1YRvLpJinJk67VF0wEZfg&s",
    title: "Scenery 3d wallpaper | homify",
    duration: "10:00",
    channel: "Shyamnarayan",
    views: "890K",
    uploadedAt: "3 years ago",
    videoUrl: "https://download.blender.org/peach/bigbuckbunny_movies/BigBuckBunny_320x180.mp4",
  },
  {
    id: 10,
    thumbnail: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRS5r-8k6FyUEN9OYQu5WgyyNqT8lrqgw7dCQ&s",
    title: "3D Nature Images | Adobe Stock",
    duration: "12:00",
    channel: "Sheru",
    views: "2.3M",
    uploadedAt: "4 years ago",
    videoUrl: "https://res.cloudinary.com/mashhuudanny/video/upload/v1720350210/xo81mxhcvjckkw1tdp62.mp4",
  },
  {
    id: 11,
    thumbnail: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQeUzhAtZL9ElXiENfplVjR5dCJsUQUG2NuXg&s",
    title: "5,364,800+ 3d Images | iStock",
    duration: "13:30",
    channel: "Moti",
    views: "760K",
    uploadedAt: "5 months ago",
    videoUrl: "https://media.w3.org/2010/05/sintel/trailer.mp4",
  },
  {
    id: 12,
    thumbnail: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQdcK3NWfTM_cOjFOH6ArcBdUbu29e0AVjFZw&s",
    title: "Understanding 3D Computer Graphics",
    duration: "20:50",
    channel: "Sandeep",
    views: "1.8M",
    uploadedAt: "2 years ago",
    videoUrl: "https://download.blender.org/peach/bigbuckbunny_movies/BigBuckBunny_320x180.mp4",
  },
];

export default videosData;